Repository andreafaith/qryptic-clearskyiq, pull requests merged in 2025-10, with the labels that each got.

#1 Frontend
  README.md
  clearskyiq/.gitignore
  clearskyiq/README.md
  clearskyiq/eslint.config.mjs
  clearskyiq/next.config.ts
  clearskyiq/package-lock.json
  clearskyiq/package.json
  clearskyiq/postcss.config.mjs
  clearskyiq/public/file.svg
  clearskyiq/public/globe.svg
  clearskyiq/public/logo.png
  clearskyiq/public/next.svg
  clearskyiq/public/vercel.svg
  clearskyiq/public/window.svg
  clearskyiq/src/app/components/footer.tsx
  clearskyiq/src/app/components/header.tsx
  clearskyiq/src/app/favicon.ico
  clearskyiq/src/app/globals.css
  clearskyiq/src/app/layout.tsx
  clearskyiq/src/app/ml/page.tsx
  clearskyiq/src/app/page.tsx
  clearskyiq/tsconfig.json
Labels: documentation, enhancement

#2 NASA TEMPO Data Visualization Integration
  clearskyiq/TEMPO_INTEGRATION.md
  clearskyiq/env.example
  clearskyiq/pnpm-lock.yaml
  clearskyiq/src/app/api/health/route.ts
  clearskyiq/src/app/api/tempo/visualize/all/route.ts
  clearskyiq/src/app/api/tempo/visualize/parallel/route.ts
  clearskyiq/src/app/api/tempo/visualize/results/[jobId]/route.ts
  clearskyiq/src/app/api/tempo/visualize/route.ts
  clearskyiq/src/app/api/tempo/visualize/status/[jobId]/route.ts
  clearskyiq/src/app/components/TempoVisualization.tsx
  clearskyiq/src/app/components/TempoVisualization/DataDescription.tsx
  clearskyiq/src/app/components/TempoVisualization/EmptyState.tsx
  clearskyiq/src/app/components/TempoVisualization/ErrorDisplay.tsx
  clearskyiq/src/app/components/TempoVisualization/HelpContent.tsx
  clearskyiq/src/app/components/TempoVisualization/LoadingState.tsx
  clearskyiq/src/app/components/TempoVisualization/VisualizationCard.tsx
  clearskyiq/src/app/components/TempoVisualization/VisualizationForm.tsx
  clearskyiq/src/app/globals.css
  clearskyiq/src/app/page.tsx
  clearskyiq/src/lib/config.ts
  harmony-api/.gitignore
  harmony-api/README.md
  harmony-api/env.example
  harmony-api/frontend_example.html
  harmony-api/main.py
  harmony-api/requirements.txt
  harmony-api/run.sh
  harmony-api/tempo_visualization.png
  harmony-api/test_api.py
  harmony-api/test_caching.py
  harmony-api/test_visualization.py
Labels: documentation, enhancement

#3 build fixes
  clearskyiq/package.json
  clearskyiq/pnpm-lock.yaml
  clearskyiq/src/app/components/TempoVisualization.tsx
  clearskyiq/src/app/components/TempoVisualization/EmptyState.tsx
  clearskyiq/src/app/components/TempoVisualization/HelpContent.tsx
  clearskyiq/src/app/ml/page.tsx
Labels: enhancement

#6 append-readme-file
  README.md
Labels: documentation
